workflow:
  rules:
    - if: $CI_COMMIT_BRANCH !== "main"
      when: never
    - when: always



executar_teste:
  before_script:
    - echo "Iniciando pipeline"
  script:
    - echo "Executando testes..."
  after_script:
   - echo "Pipeline Finalizado"
criar image:
  script:
    - echo "Criando imagens"
push image:
  script:
    - echo "Fazendo push das imagens"