

image: node.19.1

stages:
  - test
  - build
  - deploy


executar_teste:
  stage: test
  before_script:
    - echo "Iniciando pipeline"
  script:
    - echo "Executando testes..."
  after_script:
   - echo "Pipeline Finalizado"

executar_teste2:
  stage: test
  script:
    - echo "Executando testes2..."
    - npm version



criar image:
  stage: build
  script:
    - echo "Criando imagens"
push image:
  stage: deploy
  script:
    - echo "Fazendo push das imagens"